todos:
  api:
    serviceId: TODOS-API
  ui:
    serviceId: TODOS-WEBUI
spring:
  application:
    name: todos-edge
  cloud:
    gateway:
      routes:
      - id: todos_api_lb
        uri: lb://${todos.api.serviceId}
        predicates:
        - Path=/todos/**
        filters:
        - SetResponseHeader=X-TODOS-EDGE-ROUTE-ID, todos_api_lb
        - RewritePath=/todos/(?<path>.*), /$\{path}
      - id: todos_webui_lb
        uri: lb://${todos.ui.serviceId}
        predicates:
        - Path=/**
  main:
    allow-bean-definition-overriding: true
server:
  port: 9999
management:
  endpoints:
    web:
      exposure:
        include: '*'


